FROM golang:1.25-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
	go build -trimpath -ldflags="-s -w" -o /out/packplanner ./cmd/api

FROM scratch

WORKDIR /app

ENV PORT=8680

COPY --from=builder /out/packplanner ./packplanner

EXPOSE 8680

ENTRYPOINT ["/app/packplanner"]
